/**
 * Build-time custom-theme detection. Writes src/styles/theme.generated.css,
 * which globals.css imports. If src/styles/theme.custom.css exists, the shim
 * imports it; otherwise the shim is empty. This is what makes deleting the
 * custom theme graceful: there is never a dangling @import to a missing file,
 * so the build never breaks — the vanilla/custom toggle simply reports the
 * capability as unavailable (see NEXT_PUBLIC_HAS_CUSTOM_THEME in next.config).
 *
 * Runs in predev and prebuild.
 */
import fs from "node:fs";
import path from "node:path";

const stylesDir = path.resolve(process.cwd(), "src/styles");
const customPath = path.join(stylesDir, "theme.custom.css");
const generatedPath = path.join(stylesDir, "theme.generated.css");

const hasCustom = fs.existsSync(customPath);

const contents = hasCustom
  ? `/* AUTO-GENERATED by scripts/detect-theme.ts — do not edit. */\n@import "./theme.custom.css";\n`
  : `/* AUTO-GENERATED by scripts/detect-theme.ts — do not edit. */\n/* No theme.custom.css present; custom palette disabled. */\n`;

fs.mkdirSync(stylesDir, { recursive: true });
fs.writeFileSync(generatedPath, contents);

console.log(
  `theme: custom palette ${hasCustom ? "detected → enabled" : "absent → vanilla only"}`
);
